@include('layouts.partials.head')
<body>
            @include('layouts.partials.nav')
            <main>
                @yield('content')
            </main>
            @include('layouts.partials.footer')
    </body>
</html>
